version: '3'

services:
  mysql:
    container_name: ssom.local.db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "ssom"
      MYSQL_PASSWORD: "ssom"
      MYSQL_DATABASE: "ssom"
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:7.0-alpine
    container_name: ssom.local.redis
    hostname: ssom
    command: /bin/sh -c "redis-server --requirepass ssom"
    ports:
      - "6379:6379"