spring:
  profiles:
    active: local

  redis:
    host: localhost
    port: 6379
    password: ssom

  cache:
    type: redis

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/ssom
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssom
    password: ssom

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

auth:
  google:
    client-id: ${GOOGLE_CLIENT}
    client-secret: ${GOOGLE_SECRET}
    base-url: ${GOOGLE_BASE_URL}
    redirect-url: ${GOOGLE_REDIRECT}

jwt:
  refresh-time: 2592000000 # 30일
  access-time: 3600000 # 1시간
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT_SECRET}

debug: true